name: CI
on: [push, pull_request]

jobs:

  package-haxelib:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: krdlab/setup-haxe@v1
        with:
          haxe-version: 4.2.5

      - name: Set HAXEPATH
        run: |
          echo "HAXEPATH=$HAXE_STD_PATH/.." >> $GITHUB_ENV

      - name: Install Haxe dependencies
        run: |
          haxelib install openfl --quiet
          haxelib install lime --quiet
          haxelib install hxp --quiet
          haxelib install format --quiet

      - name: Rebuild swf run.n
        run: |
          haxe rebuild.hxml

      - uses: actions/upload-artifact@v4
        with:
          name: swf-haxelib
          path: |
            ./
            !tests/
            !haxe-*-*/
            !neko-*-*/
            !.git/
          if-no-files-found: error
